// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNj1cxT7P7i6eyfRdtgH3-IljVWUkQ2hY',
    appId: '1:613453056258:web:efb1f803ac8096b392da1b',
    messagingSenderId: '613453056258',
    projectId: 'userlist-project-eef24',
    authDomain: 'userlist-project-eef24.firebaseapp.com',
    storageBucket: 'userlist-project-eef24.appspot.com',
    measurementId: 'G-LPNZTQT6LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZLEQIMSbD1dMeHosePMHa_rN2Q8VxQxA',
    appId: '1:613453056258:android:6880b1244ea446dc92da1b',
    messagingSenderId: '613453056258',
    projectId: 'userlist-project-eef24',
    storageBucket: 'userlist-project-eef24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfiLprzurITremtvOaHySBMQWQogaFAhw',
    appId: '1:613453056258:ios:b847b9ba42b8fcee92da1b',
    messagingSenderId: '613453056258',
    projectId: 'userlist-project-eef24',
    storageBucket: 'userlist-project-eef24.appspot.com',
    iosClientId: '613453056258-jsg5v8opg26alp9jhrl607vi6pu8guno.apps.googleusercontent.com',
    iosBundleId: 'com.example.userlistProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfiLprzurITremtvOaHySBMQWQogaFAhw',
    appId: '1:613453056258:ios:b847b9ba42b8fcee92da1b',
    messagingSenderId: '613453056258',
    projectId: 'userlist-project-eef24',
    storageBucket: 'userlist-project-eef24.appspot.com',
    iosClientId: '613453056258-jsg5v8opg26alp9jhrl607vi6pu8guno.apps.googleusercontent.com',
    iosBundleId: 'com.example.userlistProjects',
  );
}
